# docker-compose.yml for Balena

# IMPORTANT: set environment variables in the Balena dashboard

version: '2'

networks:
  tunnel: # cloudflared tunnel ingress
  apps: # application network (leaf, code-server)
  mqtt: # mqtt network

volumes:
  repo: # github repositories: leaves, config

  # vscode editor
  code-server: # code-server configuration and files

  # homeassistant and related
  homeassistant: # homeassistant configuration
  mosquitto: # mqtt configuration
  esphome: # esphome configuration

  # certificates (certbot)
  letsencrypt: # letsencrypt certificates
  letsencrypt-log: # letsencrypt logs
  cloudflare: # cloudflare credentials

  # rclone
  rclone: # rclone configuration

services:
  # internet proxy
  tunnel:
    # IMPORTANT: set TUNNEL_TOKEN in the Balena dashboard
    container_name: tunnel
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    networks:
      - tunnel
    depends_on:
      - leaf
      - code-server

  # leaf app
  leaf:
    container_name: leaf
    image: ttmetro/leaf
    environment:
      - ENVIRONMENT=dev
      - DEPLOY_NAME=${DEPLOY_NAME}
      - DOMAIN=${DOMAIN}
      - GITHUB_ACCESS_TOKEN=${GITHUB_ACCESS_TOKEN}
      - CONFIG_DIR=/home/repo/config
      - CF_POLICY_AUD=${CF_POLICY_AUD}
      - CF_TEAM_DOMAIN=${CF_TEAM_DOMAIN}
      - CF_API_TOKEN=${CF_API_TOKEN}
      - CF_EMAIL=${CF_EMAIL}
    restart: unless-stopped
    expose:
      - 8000
    volumes:
      - repo:/home/repo # git repository
      - homeassistant:/home/homeassistant # to set permissions (in start.sh)
      - letsencrypt:/home/letsencrypt # certificates
      - cloudflare:/home/cloudflare # certbot credentials
    networks:
      - tunnel
      - apps
      - mqtt

  # editor
  code-server:
    # image: lscr.io/linuxserver/code-server:latest
    image: ttmetro/leaf-code-server:4.92.2
    container_name: ttmetro/leaf-code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/PDT
      - SUDO_PASSWORD="${SUDO_PASSWORD}"
      - DEFAULT_WORKSPACE=/home/repo/leaves
    volumes:
      - code-server:/config
      - repo:/home/repo
      - homeassistant:/home/homeassistant
      - esphome:/home/esphome
      - mosquitto:/home/mosquitto
      - letsencrypt:/home/letsencrypt
      - letsencrypt-log:/home/letsencrypt/log
    ports:
      - 8443:8443
    restart: unless-stopped
    networks:
      - tunnel
      - apps
      - mqtt

  # https://www.home-assistant.io/installation/alternative/#docker-compose
  # https://github.com/home-assistant/docker/blob/master/Dockerfile
  homeassistant:
    image: 'ghcr.io/home-assistant/home-assistant:2024.8.3'
    container_name: homeassistant
    volumes:
      - homeassistant:/config
      - /run/dbus:/run/dbus:ro
      # - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    ports:
      - 8123:8123/tcp
      - 5353:5353/tcp
      - 1900:1900/tcp
    labels:
      io.balena.features.dbus: 1
    environment:
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
    networks:
      - tunnel
      - mqtt

  mqtt:
    image: eclipse-mosquitto:2.0.18
    container_name: mqtt
    volumes:
      - mosquitto:/mosquitto
    ports:
      - 1883:1883
    restart: unless-stopped
    networks:
      - mqtt

  esphome:
    image: esphome/esphome:2024.8
    container_name: esphome
    volumes:
      - esphome:/config
    restart: unless-stopped
    ports:
      - 6052:6052
    environment:
      - TZ=America/Los_Angeles

  # letsencrypt certificate factory
  # https://eff-certbot.readthedocs.io/
  # https://www.nodinrogers.com/post/2022-03-10-certbot-cloudflare-docker/
  certbot:
    image: certbot/dns-cloudflare
    restart: no
    volumes:
      - cloudflare:/opt/cloudflare
      - letsencrypt:/etc/letsencrypt
      - letsencrypt-log:/var/log/letsencrypt

  # backup - or rather use github/cron to backup homeassistant and esphome configs?
  rclone:
    image: rclone/rclone:1.67
    container_name: rclone
    # command: rcd --rc-web-gui --rc-addr :5572 # --rc-user jsmith --rc-pass mypassword
    volumes:
      - rclone:/config/rclone
      - homeassistant:/home/homeassistant
      - esphome:/home/esphome
    restart: no
    environment:
      - PHP_TZ=America/Los_Angeles
      - PUID=1000
      - PGID=1000
