# docker-compose.yml for Balena

# IMPORTANT: set environment variables in the Balena dashboard

version: '2'

networks:
  tunnel: # cloudflared tunnel ingress
  apps: # application network (api, code-server, jupyter, rclone, letsencrypt)
  mqtt: # mqtt network

volumes:
  repo: # github repository (leaf code, public)
  config: # yaml config (github, private)

  # vscode editor
  code-server: # code-server configuration and files

  # homeassistant and related
  homeassistant: # homeassistant configuration
  mosquitto: # mqtt configuration
  esphome: # esphome configuration

  # certificates (certbot)
  letsencrypt: # letsencrypt certificates
  letsencrypt-log: # letsencrypt logs
  cloudflare: # cloudflare credentials

services:
  # internet proxy
  tunnel:
    container_name: tunnel
    image: cloudflare/cloudflared:latest
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    restart: unless-stopped
    command: tunnel run
    networks:
      - tunnel
    depends_on:
      - backend
      - jupyter
      - code-server
      - homeassistant

  # leaf app
  leaf:
    container_name: leaf
    image: ttmetro/leaf-backend
    environment:
      - ENVIRONMENT=dev
      - PROJECT_NAME=${PROJECT_NAME}
      - DOMAIN=${DOMAIN}
      - CONFIG_DIR=/home/config
      - CF_POLICY_AUD=${CF_POLICY_AUD}
      - CF_TEAM_DOMAIN=${CF_TEAM_DOMAIN}
      - CF_API_TOKEN=${CF_API_TOKEN}
      - CF_EMAIL=${CF_EMAIL}
    restart: unless-stopped
    expose:
      - 8000
    volumes:
      - repo:/home/repo # git repository
      - config:/home/config # config.json, config.yaml & backups
      - homeassistant:/home/homeassistant # to set permissions (in start.sh)
      - letsencrypt:/home/letsencrypt # certificates
      - cloudflare:/home/cloudflare # certbot credentials
    networks:
      - tunnel
      - apps
      - mqtt

  # editor
  code-server:
    # image: lscr.io/linuxserver/code-server:latest
    image: ttmetro/leaf-code-server
    container_name: ttmetro/leaf-code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/PDT
      - SUDO_PASSWORD="${SUDO_PASSWORD}"
      - DEFAULT_WORKSPACE=/home/repo
    volumes:
      - code-server:/config
      - repo:/home/repo
      - ui:/home/ui
      - config:/home/config
      - homeassistant:/home/homeassistant
      - mosquitto:/home/mosquitto
      - letsencrypt:/home/letsencrypt
      - letsencrypt-log:/home/letsencrypt/log
      - rclone:/home/rclone
    ports:
      - 8443:8443
    restart: unless-stopped
    networks:
      - tunnel
      - apps
      - mqtt
