name: Create docker image for leaf-code-server
on:
  push:
    branches:
      - main
    paths:
      - 'deploy/code-server/**'
      - 'requirements.lock'
      - 'requirements-dev.lock'
      - '.github/workflows/code-server-docker.yml'

env:
  IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/leaf-code-server

jobs:
  build:
    name: Build Docker Image for code-server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # add meta-data: https://dev.to/ken_mwaura1/automate-docker-image-builds-and-push-to-github-registry-using-github-actions-4h20
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.IMAGE }}:latest
          file: ./deploy/code-server/Dockerfile
          cache-from: type=gha
          cache-to: type=gha, mode=max
